/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author dbpan
 */
public class Figuras_geometricas extends javax.swing.JFrame {

    /**
     * Creates new form Figuras_geometricas
     */
    triangulo obj_triangulo;
    rectangulo obj_rectangulo;
    circunferencia obj_circunferencia;

    public Figuras_geometricas() {
        initComponents();
        txtRadio.setEnabled(false);
        txtAltura.setEnabled(false);
        lblRadio.setEnabled(false);
        lblAltura.setEnabled(false);
        txtLargo.setEnabled(false);
        txtAncho.setEnabled(false);
        lblAncho.setEnabled(false);
        lblLargo.setEnabled(false);
        txtRadio.setEnabled(false);
        btnCalcular.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupFiguras = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdbRectangulo = new javax.swing.JRadioButton();
        rdbCircunferencia = new javax.swing.JRadioButton();
        rdbTriangulo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lblLargo = new javax.swing.JLabel();
        lblAncho = new javax.swing.JLabel();
        lblRadio = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        txtLargo = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        txtRadio = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de figura"));

        btnGrupFiguras.add(rdbRectangulo);
        rdbRectangulo.setText("Rectángulo");
        rdbRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRectanguloActionPerformed(evt);
            }
        });

        btnGrupFiguras.add(rdbCircunferencia);
        rdbCircunferencia.setText("Circunferencia");
        rdbCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCircunferenciaActionPerformed(evt);
            }
        });

        btnGrupFiguras.add(rdbTriangulo);
        rdbTriangulo.setText("Triángulo");
        rdbTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbRectangulo)
                    .addComponent(rdbCircunferencia)
                    .addComponent(rdbTriangulo))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbRectangulo)
                .addGap(16, 16, 16)
                .addComponent(rdbCircunferencia)
                .addGap(12, 12, 12)
                .addComponent(rdbTriangulo)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Figura"));

        lblLargo.setText("Largo");

        lblAncho.setText("Ancho");

        lblRadio.setText("Radio");

        lblAltura.setText("Altura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRadio)
                            .addComponent(lblAltura))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblLargo)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAncho)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLargo)
                    .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAncho)
                    .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRadio)
                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnCalcular.setText("Calcular Área");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnSalir)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRectanguloActionPerformed
        btnCalcular.setEnabled(true);
        JTextField[] textFields = {txtAltura, txtRadio, txtLargo, txtAncho};
        for (JTextField textField : textFields) {
            textField.setText("");
        }
        if (rdbRectangulo.isSelected()) {
            txtRadio.setEnabled(false);
            txtAltura.setEnabled(false);
            lblRadio.setEnabled(false);
            lblAltura.setEnabled(false);
            txtLargo.setEnabled(true);
            txtAncho.setEnabled(true);
            lblAncho.setEnabled(true);
            lblLargo.setEnabled(true);
            txtRadio.setEnabled(false);
        }
    }//GEN-LAST:event_rdbRectanguloActionPerformed

    private void rdbCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCircunferenciaActionPerformed
        btnCalcular.setEnabled(true);
        JTextField[] textFields = {txtAltura, txtRadio, txtLargo, txtAncho};
        for (JTextField textField : textFields) {
            textField.setText("");
        }
        if (rdbCircunferencia.isSelected()) {
            txtLargo.setEnabled(false);
            txtAltura.setEnabled(false);
            txtAncho.setEnabled(false);
            lblAncho.setEnabled(false);
            lblLargo.setEnabled(false);
            lblAltura.setEnabled(false);
            lblRadio.setEnabled(true);
            txtRadio.setEnabled(true);
        }
    }//GEN-LAST:event_rdbCircunferenciaActionPerformed

    private void rdbTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTrianguloActionPerformed
        btnCalcular.setEnabled(true);
        JTextField[] textFields = {txtAltura, txtRadio, txtLargo, txtAncho};
        for (JTextField textField : textFields) {
            textField.setText("");
        }
        if (rdbTriangulo.isSelected()) {
            txtRadio.setEnabled(false);
            txtAltura.setEnabled(true);
            lblRadio.setEnabled(false);
            lblAltura.setEnabled(true);
            txtLargo.setEnabled(false);
            txtAncho.setEnabled(true);
            lblAncho.setEnabled(true);
            lblLargo.setEnabled(false);
            txtRadio.setEnabled(false);
        }
    }//GEN-LAST:event_rdbTrianguloActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //TRIANGULO
        if (rdbTriangulo.isSelected()) {
            if (txtAncho.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "EL Ancho no puede estar vacio");
                txtAncho.requestFocus();
            } else if (txtAltura.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "La Altura no puede estar vacia");
                txtAltura.requestFocus();
            } else {
                try {
                    obj_triangulo = new triangulo(Double.parseDouble(txtAltura.getText()), Double.parseDouble(txtAncho.getText()));
                    JOptionPane.showMessageDialog(rootPane, "El area del triangulo es: " + obj_triangulo.CalcularArea());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error de Calculo de area");
                }
            }
            //RECTÁNGULO
        } else if (rdbRectangulo.isSelected()) {
            if (txtLargo.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "EL Largo no puede estar vacio");
                txtLargo.requestFocus();
            } else if (txtAncho.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "EL Ancho no puede estar vacio");
                txtAncho.requestFocus();
            } else {
                try {
                    obj_rectangulo = new rectangulo(Double.parseDouble(txtLargo.getText()), Double.parseDouble(txtAncho.getText()));
                    JOptionPane.showMessageDialog(rootPane, "El area del Rectángulo es: " + obj_rectangulo.CalcularArea());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error de Calculo de area");
                }
            }
            //CIRCUNFERENCIA   
        } else if (rdbCircunferencia.isSelected()) {
            if (txtRadio.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "EL Radio no puede estar vacio");
                txtRadio.requestFocus();
            } else {
                try {
                    obj_circunferencia = new circunferencia(Double.parseDouble(txtRadio.getText()));
                    JOptionPane.showMessageDialog(rootPane, "El area dela Circunferencia es: " + obj_circunferencia.CalcularArea());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error de Calculo de area");
                }

            }
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Figuras_geometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Figuras_geometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Figuras_geometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Figuras_geometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Figuras_geometricas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup btnGrupFiguras;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblAncho;
    private javax.swing.JLabel lblLargo;
    private javax.swing.JLabel lblRadio;
    private javax.swing.JRadioButton rdbCircunferencia;
    private javax.swing.JRadioButton rdbRectangulo;
    private javax.swing.JRadioButton rdbTriangulo;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
