/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author dbpan
 */
public class frmCuenta extends javax.swing.JFrame {

    private int Cuenta;
    private String Cliente;
    private double saldo;
    /**
     * Creates new form frmCuenta
     */
    Cuenta obj_cuenta;

    public frmCuenta() {
        initComponents();
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JToggleButton();
        btnMostrar = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        jpDeposito = new javax.swing.JPanel();
        lblDeposito = new javax.swing.JLabel();
        txtDeposito = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        jRetiro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRetirar = new javax.swing.JTextField();
        btnRetirar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRetiro = new javax.swing.JButton();
        btnAhorro = new javax.swing.JButton();
        btnCheques = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Consultar Datos");
        btnMostrar.setEnabled(false);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnDeposito.setText("Realizar Deposito");
        btnDeposito.setEnabled(false);
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setToolTipText("");

        jDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblNombre.setText("Nombre");

        lblNumero.setText("Numero Cuenta");

        lblSaldo.setText("Saldo");

        javax.swing.GroupLayout jDatosLayout = new javax.swing.GroupLayout(jDatos);
        jDatos.setLayout(jDatosLayout);
        jDatosLayout.setHorizontalGroup(
            jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDatosLayout.createSequentialGroup()
                        .addComponent(lblSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDatosLayout.createSequentialGroup()
                        .addComponent(lblNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDatosLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        jDatosLayout.setVerticalGroup(
            jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Cliente", jDatos);

        jpDeposito.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblDeposito.setText("Ingrese el Monto ");

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDepositoLayout = new javax.swing.GroupLayout(jpDeposito);
        jpDeposito.setLayout(jpDepositoLayout);
        jpDepositoLayout.setHorizontalGroup(
            jpDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDepositoLayout.createSequentialGroup()
                .addGroup(jpDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDepositoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblDeposito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDepositoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jpDepositoLayout.setVerticalGroup(
            jpDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDepositoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jpDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeposito))
                .addGap(37, 37, 37)
                .addComponent(btnDepositar)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Deposito", jpDeposito);

        jLabel2.setText("Ingrese el Monto");

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jRetiroLayout = new javax.swing.GroupLayout(jRetiro);
        jRetiro.setLayout(jRetiroLayout);
        jRetiroLayout.setHorizontalGroup(
            jRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRetiroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(jRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(txtRetirar))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jRetiroLayout.setVerticalGroup(
            jRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRetiroLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnRetirar)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Retiro", jRetiro);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cuenta ");

        btnRetiro.setText("Realizar Retiro");
        btnRetiro.setEnabled(false);
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });

        btnAhorro.setText("Cuenta de ahorro");
        btnAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAhorroActionPerformed(evt);
            }
        });

        btnCheques.setText("Cheques");
        btnCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChequesActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAhorro)
                                .addGap(66, 66, 66)
                                .addComponent(btnCheques)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(55, 55, 55)
                        .addComponent(btnDeposito)
                        .addGap(44, 44, 44)
                        .addComponent(btnRetiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAhorro)
                    .addComponent(btnCheques)
                    .addComponent(btnSalir))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNombre.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "EL Nombre no puede estar vacio");
            txtNombre.requestFocus();
        } else if (txtNumero.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "El número de cuenta no puede estar vacio");
            txtNumero.requestFocus();
        } else if (txtSaldo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "El saldo no puede estar vacio");
            txtSaldo.requestFocus();
        } else {
            try {
                obj_cuenta = new Cuenta(Integer.parseInt(txtNumero.getText()), txtNombre.getText(), Double.parseDouble(txtSaldo.getText()));
                btnMostrar.setEnabled(true);
                btnDeposito.setEnabled(true);
                btnRetiro.setEnabled(true);
                Cuenta = Integer.parseInt(txtNumero.getText());
                Cliente = txtNombre.getText();
                saldo = Double.parseDouble(txtSaldo.getText());
                JTextField[] textFields = {txtNumero, txtNombre, txtSaldo};
                for (JTextField textField : textFields) {
                    textField.setText("");
                }
                JOptionPane.showMessageDialog(rootPane, "Los Datos se guardaron con éxito");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error de Calculo de area");
            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        obj_cuenta.consultarDatos();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(1, true);
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        if (txtDeposito.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "EL Monto no puede estar vacio");
            txtDeposito.requestFocus();
        } else {
            try {
                obj_cuenta.depositar(Double.parseDouble(txtDeposito.getText()));
                txtDeposito.setText("");
                JOptionPane.showMessageDialog(rootPane, "El deposito se realizo con éxito");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error de Calculo de area");
            }

        }

    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        if (txtRetirar.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "EL Monto no puede estar vacio");
            txtDeposito.requestFocus();
        } else {
            try {
                obj_cuenta.retirar(Double.parseDouble(txtRetirar.getText()));
                txtRetirar.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error de Calculo de area");
            }

        }

    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        jTabbedPane1.setEnabledAt(2, true);
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAhorroActionPerformed

        frmAhorro frm = new frmAhorro();
        frm.setDatos(Cliente, Cuenta, saldo);
        frm.setVisible(true); // Muestra el frame frmAhorro

    }//GEN-LAST:event_btnAhorroActionPerformed

    private void btnChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChequesActionPerformed
        frmCheques frm = new frmCheques();
        frm.setDatos(Cliente, Cuenta, saldo);
        frm.setVisible(true);
    }//GEN-LAST:event_btnChequesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAhorro;
    private javax.swing.JButton btnCheques;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jRetiro;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpDeposito;
    private javax.swing.JLabel lblDeposito;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtDeposito;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
